local M = {}

function M.get(palette, opts)
  local config = opts or {}
  local bg = config.transparent and "NONE" or palette.bg
  local bg_alt = config.transparent and "NONE" or palette.base2
  local bg_alt2 = config.transparent and "NONE" or palette.base1
  local bg_alt3 = config.transparent and "NONE" or palette.base3

  return {
    Normal = { fg = palette.fg, bg = bg },
    NormalNC = { fg = palette.fg, bg = bg },
    Comment = { fg = palette.base6, italic = true },
    Constant = { fg = palette.violet },
    String = { fg = palette.green },
    Character = { fg = palette.green },
    Number = { fg = palette.orange },
    Boolean = { fg = palette.orange },
    Float = { fg = palette.orange },
    Identifier = { fg = palette.cyan },
    Function = { fg = palette.blue },
    Statement = { fg = palette.magenta },
    Conditional = { fg = palette.magenta },
    Repeat = { fg = palette.magenta },
    Label = { fg = palette.violet },
    Operator = { fg = palette.magenta },
    Keyword = { fg = palette.magenta },
    Exception = { fg = palette.magenta },
    PreProc = { fg = palette.violet },
    Include = { fg = palette.violet },
    Define = { fg = palette.violet },
    Macro = { fg = palette.violet },
    PreCondit = { fg = palette.violet },
    Type = { fg = palette.yellow },
    StorageClass = { fg = palette.yellow },
    Structure = { fg = palette.yellow },
    Typedef = { fg = palette.yellow },
    Special = { fg = palette.blue },
    SpecialChar = { fg = palette.orange },
    Tag = { fg = palette.blue },
    Delimiter = { fg = palette.base7 },
    SpecialComment = { fg = palette.base6 },
    Debug = { fg = palette.red },
    Underlined = { fg = palette.blue, underline = true },
    Ignore = { fg = palette.base5 },
    Error = { fg = palette.red, bold = true },
    Todo = { fg = palette.magenta, bold = true },

    CursorLine = { bg = bg_alt },
    CursorLineNr = { fg = palette.fg },
    LineNr = { fg = palette.base5 },
    Visual = { bg = bg_alt3 },
    Search = { fg = palette.base0, bg = palette.yellow },
    IncSearch = { fg = palette.base0, bg = palette.orange },
    MatchParen = { fg = palette.cyan, bold = true },
    ColorColumn = { bg = bg_alt },
    VertSplit = { fg = palette.base4 },
    StatusLine = { fg = palette.fg, bg = bg_alt },
    StatusLineNC = { fg = palette.base6, bg = bg_alt2 },
    TabLine = { fg = palette.base6, bg = bg_alt },
    TabLineSel = { fg = palette.fg, bg = bg_alt2 },
    TabLineFill = { fg = palette.base6, bg = bg_alt2 },

    Pmenu = { fg = palette.fg, bg = bg_alt },
    PmenuSel = { fg = palette.base0, bg = palette.blue },
    PmenuSbar = { bg = bg_alt3 },
    PmenuThumb = { bg = palette.base5 },

    NormalFloat = { fg = palette.fg, bg = bg_alt },
    FloatBorder = { fg = palette.base4, bg = bg_alt },
    FloatTitle = { fg = palette.fg, bg = bg_alt },
    WinSeparator = { fg = palette.base4 },

    DiagnosticError = { fg = palette.red },
    DiagnosticWarn = { fg = palette.yellow },
    DiagnosticInfo = { fg = palette.blue },
    DiagnosticHint = { fg = palette.cyan },

    -- TreeSitter: Core captures
    ["@comment"] = { link = "Comment" },
    ["@constant"] = { link = "Constant" },
    ["@constant.builtin"] = { fg = palette.orange },
    ["@string"] = { link = "String" },
    ["@string.escape"] = { fg = palette.orange },
    ["@string.special"] = { fg = palette.orange },
    ["@number"] = { link = "Number" },
    ["@boolean"] = { link = "Boolean" },
    ["@function"] = { link = "Function" },
    ["@function.builtin"] = { fg = palette.blue },
    ["@function.call"] = { fg = palette.blue },
    ["@keyword"] = { link = "Keyword" },
    ["@keyword.return"] = { fg = palette.magenta },
    ["@keyword.operator"] = { fg = palette.magenta },
    ["@type"] = { link = "Type" },
    ["@type.builtin"] = { fg = palette.yellow },
    ["@variable"] = { fg = palette.fg },
    ["@variable.builtin"] = { fg = palette.orange },
    ["@variable.parameter"] = { fg = palette.red },
    ["@property"] = { fg = palette.fg },
    ["@operator"] = { link = "Operator" },
    ["@punctuation.bracket"] = { fg = palette.base7 },
    ["@punctuation.delimiter"] = { fg = palette.base7 },
    ["@punctuation.special"] = { fg = palette.blue },
    ["@tag"] = { fg = palette.red },
    ["@tag.attribute"] = { fg = palette.yellow },
    ["@tag.delimiter"] = { fg = palette.base7 },
    ["@module"] = { fg = palette.yellow },
    ["@label"] = { link = "Label" },

    -- TreeSitter: Markup (Markdown, RST, etc.)
    ["@markup.heading"] = { fg = palette.blue, bold = true },
    ["@markup.heading.1"] = { fg = palette.red, bold = true },
    ["@markup.heading.2"] = { fg = palette.orange, bold = true },
    ["@markup.heading.3"] = { fg = palette.yellow, bold = true },
    ["@markup.heading.4"] = { fg = palette.green, bold = true },
    ["@markup.heading.5"] = { fg = palette.blue, bold = true },
    ["@markup.heading.6"] = { fg = palette.magenta, bold = true },
    ["@markup.strong"] = { bold = true },
    ["@markup.italic"] = { italic = true },
    ["@markup.strikethrough"] = { strikethrough = true },
    ["@markup.underline"] = { underline = true },
    ["@markup.link"] = { fg = palette.cyan },
    ["@markup.link.label"] = { fg = palette.blue, underline = true },
    ["@markup.link.url"] = { fg = palette.dark_cyan, underline = true },
    ["@markup.raw"] = { fg = palette.teal },
    ["@markup.raw.block"] = { fg = palette.teal },
    ["@markup.list"] = { fg = palette.blue },
    ["@markup.list.checked"] = { fg = palette.green },
    ["@markup.list.unchecked"] = { fg = palette.base5 },
    ["@markup.quote"] = { fg = palette.base6, italic = true },
    ["@markup.math"] = { fg = palette.violet },

    -- Legacy Vim: Markdown syntax groups
    markdownH1 = { fg = palette.red, bold = true },
    markdownH2 = { fg = palette.orange, bold = true },
    markdownH3 = { fg = palette.yellow, bold = true },
    markdownH4 = { fg = palette.green, bold = true },
    markdownH5 = { fg = palette.blue, bold = true },
    markdownH6 = { fg = palette.magenta, bold = true },
    markdownHeadingDelimiter = { fg = palette.base5, bold = true },
    markdownHeadingRule = { fg = palette.base5 },
    markdownBold = { bold = true },
    markdownItalic = { italic = true },
    markdownBoldItalic = { bold = true, italic = true },
    markdownCode = { fg = palette.teal },
    markdownCodeBlock = { fg = palette.teal },
    markdownCodeDelimiter = { fg = palette.teal },
    markdownUrl = { fg = palette.dark_cyan, underline = true },
    markdownUrlTitle = { fg = palette.green },
    markdownLink = { fg = palette.blue, underline = true },
    markdownLinkText = { fg = palette.blue, underline = true },
    markdownListMarker = { fg = palette.blue },
    markdownOrderedListMarker = { fg = palette.blue },
    markdownBlockquote = { fg = palette.base6, italic = true },
    markdownRule = { fg = palette.base5 },
    markdownFootnote = { fg = palette.dark_cyan },
    markdownEscape = { fg = palette.orange },

    TelescopeNormal = { fg = palette.fg, bg = bg_alt },
    TelescopeBorder = { fg = palette.base4, bg = bg_alt },
    TelescopePromptNormal = { fg = palette.fg, bg = bg_alt },
    TelescopePromptBorder = { fg = palette.base4, bg = bg_alt },
    TelescopeResultsNormal = { fg = palette.fg, bg = bg_alt },
    TelescopeResultsBorder = { fg = palette.base4, bg = bg_alt },
    TelescopePreviewNormal = { fg = palette.fg, bg = bg_alt },
    TelescopePreviewBorder = { fg = palette.base4, bg = bg_alt },
    TelescopeTitle = { fg = palette.magenta, bold = true },
    TelescopePromptTitle = { fg = palette.blue, bold = true },
    TelescopeResultsTitle = { fg = palette.green, bold = true },
    TelescopePreviewTitle = { fg = palette.yellow, bold = true },
    TelescopeMatching = { fg = palette.orange, bold = true },
    TelescopeSelection = { fg = palette.fg, bg = bg_alt3 },
    TelescopeSelectionCaret = { fg = palette.cyan, bold = true },

    OilDir = { link = "Directory" },
    OilFile = { link = "Normal" },
    OilHidden = { link = "Comment" },
    OilLink = { link = "Underlined" },
    OilTitle = { link = "Title" },
    OilPreview = { link = "NormalFloat" },

    FzfLuaNormal = { fg = palette.fg, bg = bg_alt },
    FzfLuaBorder = { fg = palette.base4, bg = bg_alt },
    FzfLuaTitle = { fg = palette.magenta, bold = true },
    FzfLuaHeader = { fg = palette.violet },
    FzfLuaPath = { fg = palette.blue },
    FzfLuaCursorLine = { fg = palette.fg, bg = bg_alt3 },
    FzfLuaCursorLineNr = { fg = palette.cyan },
    FzfLuaSearch = { fg = palette.orange },
    FzfLuaPrompt = { fg = palette.green },
    FzfNormal = { fg = palette.fg, bg = bg_alt },
    FzfBorder = { fg = palette.base4, bg = bg_alt },
  }
end

return M
